"""
evaluate_agent.py
─────────────────────────────────────────────────────────────────────────────
Full evaluation of EmotionAgent on the IEMOCAP fold-1 test set.

TEST SET: Session 1 (1097 utterances). This is the identical partition used
during fold-1 fusion training — get_split_dfs(df, fold=1) returns test=S1,
val=S2, train=S3/S4/S5. The kNN index was built from the training partition
only, so there is zero overlap between retrieved evidence and test inputs.

BASELINE: fold-1 fusion test MacF1 = 0.748 (from src/outputs/fusion/fold1_test_metrics.json).
The agent loads the same checkpoint weights, so classification results should
be numerically identical. Any divergence indicates a preprocessing difference
worth investigating.

NEW METRIC — Retrieval Agreement Rate:
  For each utterance, fraction of top-5 kNN neighbors sharing the GROUND TRUTH
  label (not the prediction). This measures whether the retrieval index would
  have provided correct evidence, independently of whether the classifier agreed.

  Stratified by classifier outcome:
    - Correct predictions: does retrieval reinforce the right answer?
    - Wrong predictions:   does retrieval show the correct label anyway?
      ("retrieval rescue rate" — evidence the RAG component could catch errors)

Run from project root:
    python agentic_ai/evaluate_agent.py               # test set (default)
    python agentic_ai/evaluate_agent.py --split val   # val set (for alert threshold tuning)
    python agentic_ai/evaluate_agent.py --split test  # explicit test set

NOTE ON fold1_val_agent_eval.csv
──────────────────────────────────
This file was originally generated by an ad-hoc inline script during the
alert-rule threshold-tuning session (not by this script). Running:
    python agentic_ai/evaluate_agent.py --split val
will regenerate it reproducibly from here on.
"""

import sys
import json
import argparse
import pathlib
from collections import defaultdict

import numpy as np
import pandas as pd
from tqdm import tqdm

# ── src/ on path ───────────────────────────────────────────────────────────
_PROJECT_ROOT = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(_PROJECT_ROOT / "src"))
sys.path.insert(0, str(_PROJECT_ROOT))   # makes `agentic_ai` importable as a package

from config import IDX_TO_LABEL, NUM_CLASSES              # noqa: E402
from data_preprocessing import load_metadata, get_split_dfs  # noqa: E402
from metrics import compute_metrics                        # noqa: E402

from agentic_ai.agent import EmotionAgent                 # noqa: E402

_OUTPUT_DIR = _PROJECT_ROOT / "agentic_ai" / "outputs"
_BASELINE_PATH = _PROJECT_ROOT / "src" / "outputs" / "fusion" / "fold1_test_metrics.json"
_EMOTION_CLASSES = [IDX_TO_LABEL[i] for i in range(NUM_CLASSES)]


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--fold",  type=int, default=1,
                   help="LOSO fold to evaluate (default: 1)")
    p.add_argument("--split", choices=["train", "val", "test"], default="test",
                   help="Which split to run on (default: test). "
                        "Use 'val' to regenerate fold1_val_agent_eval.csv for alert tuning.")
    return p.parse_args()


# ─────────────────────────────────────────────────────────────────────────────
# RETRIEVAL METRICS
# ─────────────────────────────────────────────────────────────────────────────

def retrieval_agreement(neighbor_labels: list, ground_truth: str) -> float:
    """Fraction of top-k retrieved neighbors whose label matches ground truth."""
    if not neighbor_labels:
        return 0.0
    return sum(1 for lbl in neighbor_labels if lbl == ground_truth) / len(neighbor_labels)


def compute_retrieval_summary(records: list) -> dict:
    """
    Computes overall and stratified retrieval agreement statistics.

    'Retrieval rescue rate': among utterances where the classifier was WRONG,
    what fraction had at least one retrieved neighbor labeled with the correct
    emotion? A high rescue rate means the RAG evidence could flag classifier
    errors to a downstream reasoning agent (Agent 4/5).
    """
    all_agree       = [r["retrieval_agreement"] for r in records]
    correct_agree   = [r["retrieval_agreement"] for r in records if r["correct"]]
    incorrect_agree = [r["retrieval_agreement"] for r in records if not r["correct"]]

    # Rescue rate: wrong prediction but ≥1 neighbor has correct label
    n_wrong   = sum(1 for r in records if not r["correct"])
    n_rescued = sum(
        1 for r in records
        if not r["correct"] and any(
            lbl == r["ground_truth"] for lbl in r["neighbor_labels"]
        )
    )

    # Per-class retrieval agreement (ground-truth class perspective)
    per_class = defaultdict(list)
    for r in records:
        per_class[r["ground_truth"]].append(r["retrieval_agreement"])
    per_class_mean = {cls: float(np.mean(vals)) for cls, vals in per_class.items()}

    return {
        "retrieval_agreement_overall":         float(np.mean(all_agree)),
        "retrieval_agreement_when_correct":    float(np.mean(correct_agree))   if correct_agree   else None,
        "retrieval_agreement_when_incorrect":  float(np.mean(incorrect_agree)) if incorrect_agree else None,
        "retrieval_rescue_rate": (n_rescued / n_wrong) if n_wrong > 0 else None,
        "n_wrong":   n_wrong,
        "n_rescued": n_rescued,
        "retrieval_agreement_per_class": per_class_mean,
    }


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    fold  = args.fold
    split = args.split

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Load requested split ───────────────────────────────────────────────
    meta_path = str(_PROJECT_ROOT / "src" / "data_splits" / "iemocap_metadata.csv")
    df = load_metadata(meta_path)
    train_df, val_df, test_df = get_split_dfs(df, fold=fold)
    eval_df = {"train": train_df, "val": val_df, "test": test_df}[split]
    eval_df = eval_df[eval_df["audio_exists"]].reset_index(drop=True)

    print(f"\n[evaluate_agent] Fold {fold} {split} set: {len(eval_df)} utterances "
          f"(session {sorted(eval_df['session'].unique())})")
    print(f"  Class distribution: "
          + ", ".join(f"{e}={n}" for e, n in eval_df["emotion"].value_counts().items()))

    # Confirm zero overlap between kNN index (train sessions) and eval split
    train_ids = set(train_df["utterance_id"])
    eval_ids  = set(eval_df["utterance_id"])
    overlap   = train_ids & eval_ids
    assert len(overlap) == 0, f"BUG: {len(overlap)} utterances appear in both train index and {split} set"
    print(f"  kNN index / {split} overlap: 0 utterances ✓")

    # ── Initialise agent ───────────────────────────────────────────────────
    print(f"\n[evaluate_agent] Loading EmotionAgent (fold={fold}, k=5) ...")
    agent = EmotionAgent(fold=fold, k=5)

    # ── Run inference on every utterance in the requested split ───────────
    records = []
    rows    = eval_df.to_dict("records")

    for row in tqdm(rows, desc="Inferring"):
        try:
            result = agent(audio_path=row["audio_path"], text=row["text"])
        except Exception as e:
            print(f"[WARN] Skipping {row['utterance_id']}: {e}")
            continue

        neighbor_labels = [ex.emotion for ex in result.retrieved_examples]
        gt              = row["emotion"]
        pred            = result.predicted_emotion
        correct         = (pred == gt)
        agree           = retrieval_agreement(neighbor_labels, gt)

        records.append({
            "utterance_id":        row["utterance_id"],
            "ground_truth":        gt,
            "predicted":           pred,
            "correct":             correct,
            "retrieval_agreement": agree,
            "neighbor_labels":     neighbor_labels,
            # Per-class probabilities as individual columns
            **{f"p_{cls}": result.class_probabilities.get(cls, 0.0)
               for cls in _EMOTION_CLASSES},
        })

    print(f"\n[evaluate_agent] Completed: {len(records)}/{len(rows)} utterances")

    # ── Classification metrics (same compute_metrics as train.py) ─────────
    y_true = [r["ground_truth"] for r in records]
    y_pred = [r["predicted"]    for r in records]

    # compute_metrics expects integer labels
    from config import LABEL_TO_IDX
    y_true_idx = [LABEL_TO_IDX[y] for y in y_true]
    y_pred_idx = [LABEL_TO_IDX[y] for y in y_pred]

    # Dummy loss (not available at agent inference time)
    clf_metrics = compute_metrics(y_true_idx, y_pred_idx)

    # ── Retrieval metrics ──────────────────────────────────────────────────
    ret_metrics = compute_retrieval_summary(records)

    # ── Load baseline for comparison ───────────────────────────────────────
    baseline = None
    if _BASELINE_PATH.exists():
        with open(_BASELINE_PATH) as f:
            baseline = json.load(f)

    # ── Print report ───────────────────────────────────────────────────────
    print("\n" + "="*70)
    print(f"  FOLD {fold} AGENT EVALUATION — CLASSIFICATION METRICS")
    print("="*70)

    header = f"  {'Metric':<22} {'Agent':>10}"
    if baseline:
        header += f"  {'Baseline (fusion)':>18}  {'Delta':>8}"
    print(header)
    print("  " + "-"*62)

    def compare_row(label, agent_val, base_key):
        base_val = baseline.get(base_key) if baseline else None
        row = f"  {label:<22} {agent_val:>10.4f}"
        if base_val is not None:
            delta = agent_val - base_val
            row += f"  {base_val:>18.4f}  {delta:>+8.4f}"
        print(row)

    compare_row("Macro F1",      clf_metrics["macro_f1"],      "macro_f1")
    compare_row("Weighted F1",   clf_metrics["weighted_f1"],   "weighted_f1")
    compare_row("Weighted Acc",  clf_metrics["weighted_acc"],  "weighted_acc")
    compare_row("Unweighted Acc",clf_metrics["unweighted_acc"],"unweighted_acc")

    print("\n  Per-class F1:")
    for cls in _EMOTION_CLASSES:
        agent_f1 = clf_metrics["f1_per_class"].get(cls, 0.0)
        base_f1  = baseline["f1_per_class"].get(cls) if baseline else None
        row = f"    {cls:>10}  {agent_f1:6.4f}"
        if base_f1 is not None:
            row += f"  (baseline {base_f1:.4f}, Δ{agent_f1-base_f1:+.4f})"
        print(row)

    print("\n  Confusion matrix (rows=true, cols=pred):")
    from sklearn.metrics import confusion_matrix as cm_fn
    conf = cm_fn(y_true, y_pred, labels=_EMOTION_CLASSES)
    header_str = "  " + " "*10 + "".join(f"{c[:5]:>7}" for c in _EMOTION_CLASSES)
    print(header_str)
    for i, cls in enumerate(_EMOTION_CLASSES):
        print(f"  {cls:>10}" + "".join(f"{conf[i,j]:>7d}" for j in range(len(_EMOTION_CLASSES))))

    print("\n" + "="*70)
    print(f"  RETRIEVAL AGREEMENT METRICS")
    print("="*70)
    print(f"  Overall mean agreement (top-5 neighbors vs ground truth):")
    print(f"    All utterances   : {ret_metrics['retrieval_agreement_overall']:.3f}")
    print(f"    Correct preds    : {ret_metrics['retrieval_agreement_when_correct']:.3f}")
    print(f"    Incorrect preds  : {ret_metrics['retrieval_agreement_when_incorrect']:.3f}")
    print()
    print(f"  Retrieval rescue rate (wrong pred, ≥1 neighbor = correct label):")
    print(f"    {ret_metrics['n_rescued']}/{ret_metrics['n_wrong']} wrong predictions "
          f"had correct label in top-5  →  {ret_metrics['retrieval_rescue_rate']:.1%}")
    print()
    print(f"  Per-class retrieval agreement:")
    for cls in _EMOTION_CLASSES:
        val = ret_metrics["retrieval_agreement_per_class"].get(cls, 0.0)
        bar = "█" * int(val * 20)
        print(f"    {cls:>10}  {val:.3f}  {bar}")

    # ── Save CSV ───────────────────────────────────────────────────────────
    csv_rows = []
    for r in records:
        csv_rows.append({
            "utterance_id":        r["utterance_id"],
            "ground_truth":        r["ground_truth"],
            "predicted":           r["predicted"],
            "correct":             r["correct"],
            "retrieval_agreement": r["retrieval_agreement"],
            "neighbor_labels":     ";".join(r["neighbor_labels"]),
            **{f"p_{cls}": r[f"p_{cls}"] for cls in _EMOTION_CLASSES},
        })
    csv_path = _OUTPUT_DIR / f"fold{fold}_{split}_agent_eval.csv"
    pd.DataFrame(csv_rows).to_csv(csv_path, index=False)
    print(f"\n[evaluate_agent] Per-utterance CSV saved: {csv_path}")

    # ── Save summary JSON ──────────────────────────────────────────────────
    summary = {
        "fold":               fold,
        "n_test_utterances":  len(records),
        "classification":     {k: v for k, v in clf_metrics.items() if k != "loss"},
        "retrieval":          ret_metrics,
        "baseline_macro_f1":  baseline["macro_f1"] if baseline else None,
        "delta_macro_f1":     (clf_metrics["macro_f1"] - baseline["macro_f1"])
                              if baseline else None,
    }
    def _json_safe(obj):
        if isinstance(obj, (np.integer,)): return int(obj)
        if isinstance(obj, (np.floating,)): return float(obj)
        if isinstance(obj, np.ndarray): return obj.tolist()
        raise TypeError(f"Not serializable: {type(obj)}")

    json_path = _OUTPUT_DIR / f"fold{fold}_{split}_agent_summary.json"
    with open(json_path, "w") as f:
        json.dump(summary, f, indent=2, default=_json_safe)
    print(f"[evaluate_agent] Summary JSON saved:      {json_path}\n")


if __name__ == "__main__":
    main()
